apiVersion: v1
kind: Service
metadata:
  name: carta-dev-service
spec:
  selector:
    app: carta-dev
  ports:
  - protocol: "TCP"
    port: 3002
    targetPort: 3002
  type: LoadBalancer 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carta-dev
spec:
  selector:
    matchLabels:
      app: carta-dev
  replicas: 2
  template:
    metadata:
      labels:
        app: carta-dev
    spec:
      containers:
      - name: carta-dev
        image: carta-dev:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
        volumeMounts:
        - mountPath: /Images
          name: images
      volumes:
      - name: images
        hostPath: 
          path: /Images
          type: Directory